apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.nginx.sparkHost }}
    external-dns.alpha.kubernetes.io/ttl: "120"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.nginx.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: spark-gateway
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.nginx.sparkHost }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: spark-master-svc
                port:
                  number: 80
  tls:
  - hosts:
    - {{ .Values.nginx.sparkHost }}
    secretName: tls-secret 