apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, PATCH, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.nginx.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1/$2$3$4
  name: swagger-web-api-gateway
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.nginx.host }}
      http:
        paths:
          {{- range .Values.nginx.services }}
          - path: /({{ . }})/(swagger-ui|api-docs)(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ . }}-service
                port:
                  number: 8080
          {{- end }}